stages:
  - Security_Review
  - SonarCloud

variables:
  SONAR_USER_HOME: '${CI_PROJECT_DIR}/.sonar'
  GIT_DEPTH: '0'

sonarcloud-check:
  stage: SonarCloud
  image:
    name: sonarsource/sonar-scanner-cli:latest
    entrypoint: ['']
  cache:
    key: '${CI_JOB_NAME}'
    paths:
      - .sonar/cache
  script:
    - sonar-scanner
  only:
    - master
    - merge_requests
    - develop

check-code:
 stage: Security_Review
 before_script:
   - "git clone https://gitlab.com/acct.global/acct.vtexio-projects/graphql-training.git"
 script:
   - cp graphql-training/security-review/main.py .
   - rm -rf graphql-training
   - python3 main.py
   - rm main.py
 only:
    - master
    - merge_requests
    - develop

